sudo: required

services:
  - docker
  
script:
  - docker info
  - docker --version
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t djx339/torch torch/
  - docker push djx339/torch
